server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

openai:
  api-key: ${OPENAI_API_KEY:YOUR_API_KEY_HERE}
  base-url: https://api.openai.com/v1
  model: gpt-4o-mini
  temperature: 0.7